### ISSUE TITLE
DOC: Unexpected results from momepy.COINS

### ISSUE THREAD

**Issue by mohdalattar** [pysal/momepy#448]
### Describe the problem

Hi I ran the the following code to quantify street continuity in Manhattan. However, the results were not as I expected 

Not sure why some street falls into 1 - 22 and others in 22-86. 

<img width="1222" alt="Screen Shot 2022-12-17 at 9 48 47 PM" src="https://user-images.githubusercontent.com/50058721/208257017-0a517068-f972-4047-9302-48b0df8939e6.png">

I was expected that based street will be categorized based on the continuity length  . Any interpretation why I am getting this? 

Not sure the bold red line is not including the remaining segment:

<img width="476" alt="Screen Shot 2022-12-17 at 9 54 15 PM" src="https://user-images.githubusercontent.com/50058721/208257280-f050657f-7b37-49db-aecb-15d0068f868d.png">

Similarly for this segment:
<img width="428" alt="Screen Shot 2022-12-17 at 9 55 53 PM" src="https://user-images.githubusercontent.com/50058721/208257300-8001d952-ce45-4216-9849-6c282b848856.png">

### Steps to reproduce

import networkx as nx
import OSMnx as ox 
import momepy 

streets = ox.graph_from_place('Manhattan', network_type='drive')
edges = ox.graph_to_gdfs(streets, nodes=False, edges=True,
                                   node_geometry=False, fill_edge_geometry=True)
continuity = momepy.COINS(edges)
stroke_gdf = continuity.stroke_gdf()
stroke_gdf
stroke_gdf.to_csv('Manhattan.csv')

### Versions of your packages

momepy = 0.5.4
networkx = 2.8.8
geopandas = 0.12.2
libpysal = 4.6.2

**Comment by martinfleis** [comment]
@amorfinv any idea?

**Comment by amorfinv** [comment]
Hello, @martinfleis and @mohdalattar,

Very odd. At first I thought it might be due to commit 6b7bd8d. However, it seems like it is unrelated to that specific fix. So then I used an undirected graph as that is what I usually work with and everything seems ok there. It still might be related to indexing.

Here is the code that gives the expected result,

```python
import networkx as nx
import OSMnx as ox
import momepy

G = ox.graph_from_place('Manhattan', network_type='drive')
streets = ox.get_undirected(G)
edges = ox.graph_to_gdfs(streets, nodes=False, edges=True, node_geometry=False, fill_edge_geometry=True)
continuity = momepy.COINS(edges)
stroke_gdf = continuity.stroke_gdf()
stroke_gdf.to_csv('Manhattan.csv')
```

<img width="694" alt="image" src="https://user-images.githubusercontent.com/78442543/208296132-69594e82-f780-4ce0-bf7f-3e1ebecda344.png">

Manhattan should only give 1017 stroke groups. However, with a directed graph there are 7995 stroke groups.

I think I will have some time later in the week to try and fix it for directed graphs. However, @mohdalattar, if you don't need a directed graph then I suggest converting it to undirected before you run ```COINS```.

-Andres

**Comment by amorfinv** [comment]
I thought about it a bit more. It might be failing because ```osmnx``` gives a ```MultiDirected``` ```nx``` graph. So there are probably a couple of places where you have parallel edges with overlapping geometry. ```osmnx``` returns a ```MultiGraph``` when you use ```ox.get_undirected()``` (see [here](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.utils_graph.get_undirected)) and only maintains the geometry of parallel edges if the geometry is different.

Gut feeling is that ```COINS``` should work for a ```GeoDataFrame``` prepared with following ```nx``` graphs:

1. ```Graph```. 
2. ```DirectedGraph```.
3. ```MultiGraph``` that only has parallel edges if the geometries are different.
4. ```MultiDirectedGraph``` that only has parallel edges if the geometries are different.

@martinfleis, I can test the theory to make sure but perhaps there should be something in the docs explaining this?

**Comment by mohdalattar** [comment]
Hello @amorfinv , your approach [ using undirected graph ] is exactly as I expected ! thank you so much

**Comment by amorfinv** [comment]
Ok last update haha...I think I could also make it work for any ```MultiDirectedGraph``` or ```MultiGraph``` with parallel edges with overlapping geometry. Would just need to explain that the ```stroke_gdf``` merges parallel edges with overlapping geometry. And that if you get the total length of a stroke group via the attributes then it will double lengths at these edges.

**Comment by mohdalattar** [comment]
I am happy with using undirected because it maintains the street geometry and accordingly assign a score for the street continuity. I believe this approach matches the intuitive definition of street continuity.

**Comment by martinfleis** [comment]
@amorfinv keep in mind that momepy does not take osmnx object as an input for COINS but a GeoDataFrame. Such a gdf is expected not to contain geometries being _duplicated_ (technically they're not duplicate due to the order of coordinates but practically they are treated as such). One and only thing I would do on our side is to add a note to the documentation explaining this exception together with the snippet you posted above casting graph to undirected as a solution for osmnx. 

I am also not excited about the way osmnx creates geodataframe from directed graphs as it is a bit unconventional. Often you have non-duplicated geometries with attributes like `direction={`forwards', 'backwards', 'both'}` denoting the directionality. What osmnx is doing then creates problems like the one reported here.

**Comment by amorfinv** [comment]
Ok that makes sense. Then the example in the user guide probably needs the casting to undirected in it as well.
