### ISSUE TITLE
can't write to a  .graphml  file

### ISSUE THREAD

**Issue by studentdsx** [pysal/momepy#523]
### Describe the problem

![image](https://github.com/pysal/momepy/assets/12723249/dd9f98b5-b2e9-406b-b761-35ba017a4bfd)

### Steps to reproduce

ftc = gpd.read_file("ftc_link_single.json")
G = momepy.gdf_to_nx(ftc, approach="primal",directed=True,oneway_column="DIR")
nx.write_graphml(G, "./ftc.graphml")

### Versions of your packages

momepy=0.6.0

**Comment by martinfleis** [comment]
GraphML does not support serialising CRS information that is attached to the graph to allow geospatial operations. It probably won't support geometries attached to edges either. If you want to save your graph as GraphML you will need to drop these from the graph. 

This is an expected behaviour resulting from limitations of GraphML in combination with custom data used by momepy.
